using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ScriptureGraph.Core.Training
{
    public static class HymnMetadataEnglish
    {
        private static Tuple<string, int>[] ENGLISH_HYMNAL = new Tuple<string, int>[]
        {
            new Tuple<string, int>( "the-morning-breaks", 1 ),
            new Tuple<string, int>( "the-spirit-of-god", 2 ),
            new Tuple<string, int>( "now-let-us-rejoice", 3 ),
            new Tuple<string, int>( "truth-eternal", 4 ),
            new Tuple<string, int>( "high-on-the-mountain-top", 5 ),
            new Tuple<string, int>( "redeemer-of-israel", 6 ),
            new Tuple<string, int>( "israel-israel-god-is-calling", 7 ),
            new Tuple<string, int>( "awake-and-arise", 8 ),
            new Tuple<string, int>( "come-rejoice", 9 ),
            new Tuple<string, int>( "come-sing-to-the-lord", 10 ),
            new Tuple<string, int>( "what-was-witnessed-in-the-heavens", 11 ),
            new Tuple<string, int>( "twas-witnessed-in-the-morning-sky", 12 ),
            new Tuple<string, int>( "an-angel-from-on-high", 13 ),
            new Tuple<string, int>( "sweet-is-the-peace-the-gospel-brings", 14 ),
            new Tuple<string, int>( "i-saw-a-mighty-angel-fly", 15 ),
            new Tuple<string, int>( "what-glorious-scenes-mine-eyes-behold", 16 ),
            new Tuple<string, int>( "awake-ye-saints-of-god-awake", 17 ),
            new Tuple<string, int>( "the-voice-of-god-again-is-heard", 18 ),
            new Tuple<string, int>( "we-thank-thee-o-god-for-a-prophet", 19 ),
            new Tuple<string, int>( "god-of-power-god-of-right", 20 ),
            new Tuple<string, int>( "come-listen-to-a-prophets-voice", 21 ),
            new Tuple<string, int>( "we-listen-to-a-prophets-voice", 22 ),
            new Tuple<string, int>( "we-ever-pray-for-thee", 23 ),
            new Tuple<string, int>( "god-bless-our-prophet-dear", 24 ),
            new Tuple<string, int>( "now-well-sing-with-one-accord", 25 ),
            new Tuple<string, int>( "joseph-smiths-first-prayer", 26 ),
            new Tuple<string, int>( "praise-to-the-man", 27 ),
            new Tuple<string, int>( "saints-behold-how-great-jehovah", 28 ),
            new Tuple<string, int>( "a-poor-wayfaring-man-of-grief", 29 ),
            new Tuple<string, int>( "come-come-ye-saints", 30 ),
            new Tuple<string, int>( "o-god-our-help-in-ages-past", 31 ),
            new Tuple<string, int>( "the-happy-day-at-last-has-come", 32 ),
            new Tuple<string, int>( "our-mountain-home-so-dear", 33 ),
            new Tuple<string, int>( "o-ye-mountains-high", 34 ),
            new Tuple<string, int>( "for-the-strength-of-the-hills", 35 ),
            new Tuple<string, int>( "they-the-builders-of-the-nation", 36 ),
            new Tuple<string, int>( "the-wintry-day-descending-to-its-close", 37 ),
            new Tuple<string, int>( "come-all-ye-saints-of-zion", 38 ),
            new Tuple<string, int>( "o-saints-of-zion", 39 ),
            new Tuple<string, int>( "arise-o-glorious-zion", 40 ),
            new Tuple<string, int>( "let-zion-in-her-beauty-rise", 41 ),
            new Tuple<string, int>( "hail-to-the-brightness-of-zions-glad-morning", 42 ),
            new Tuple<string, int>( "zion-stands-with-hills-surrounded", 43 ),
            new Tuple<string, int>( "beautiful-zion-built-above", 44 ),
            new Tuple<string, int>( "lead-me-into-life-eternal", 45 ),
            new Tuple<string, int>( "glorious-things-of-thee-are-spoken", 46 ),
            new Tuple<string, int>( "we-will-sing-of-zion", 47 ),
            new Tuple<string, int>( "glorious-things-are-sung-of-zion", 48 ),
            new Tuple<string, int>( "adam-ondi-ahman", 49 ),
            new Tuple<string, int>( "come-thou-glorious-day-of-promise", 50 ),
            new Tuple<string, int>( "sons-of-michael-he-approaches", 51 ),
            new Tuple<string, int>( "the-day-dawn-is-breaking", 52 ),
            new Tuple<string, int>( "let-earths-inhabitants-rejoice", 53 ),
            new Tuple<string, int>( "behold-the-mountain-of-the-lord", 54 ),
            new Tuple<string, int>( "lo-the-mighty-god-appearing", 55 ),
            new Tuple<string, int>( "softly-beams-the-sacred-dawning", 56 ),
            new Tuple<string, int>( "were-not-ashamed-to-own-our-lord", 57 ),
            new Tuple<string, int>( "come-ye-children-of-the-lord", 58 ),
            new Tuple<string, int>( "come-o-thou-king-of-kings", 59 ),
            new Tuple<string, int>( "battle-hymn-of-the-republic", 60 ),
            new Tuple<string, int>( "raise-your-voices-to-the-lord", 61 ),
            new Tuple<string, int>( "all-creatures-of-our-god-and-king", 62 ),
            new Tuple<string, int>( "great-king-of-heaven", 63 ),
            new Tuple<string, int>( "on-this-day-of-joy-and-gladness", 64 ),
            new Tuple<string, int>( "come-all-ye-saints-who-dwell-on-earth", 65 ),
            new Tuple<string, int>( "rejoice-the-lord-is-king", 66 ),
            new Tuple<string, int>( "glory-to-god-on-high", 67 ),
            new Tuple<string, int>( "a-mighty-fortress-is-our-god", 68 ),
            new Tuple<string, int>( "all-glory-laud-and-honor", 69 ),
            new Tuple<string, int>( "sing-praise-to-him", 70 ),
            new Tuple<string, int>( "with-songs-of-praise", 71 ),
            new Tuple<string, int>( "praise-to-the-lord-the-almighty", 72 ),
            new Tuple<string, int>( "praise-the-lord-with-heart-and-voice", 73 ),
            new Tuple<string, int>( "praise-ye-the-lord", 74 ),
            new Tuple<string, int>( "in-hymns-of-praise", 75 ),
            new Tuple<string, int>( "god-of-our-fathers-we-come-unto-thee", 76 ),
            new Tuple<string, int>( "great-is-the-lord", 77 ),
            new Tuple<string, int>( "god-of-our-fathers-whose-almighty-hand", 78 ),
            new Tuple<string, int>( "with-all-the-power-of-heart-and-tongue", 79 ),
            new Tuple<string, int>( "god-of-our-fathers-known-of-old", 80 ),
            new Tuple<string, int>( "press-forward-saints", 81 ),
            new Tuple<string, int>( "for-all-the-saints", 82 ),
            new Tuple<string, int>( "guide-us-o-thou-great-jehovah", 83 ),
            new Tuple<string, int>( "faith-of-our-fathers", 84 ),
            new Tuple<string, int>( "how-firm-a-foundation", 85 ),
            new Tuple<string, int>( "how-great-thou-art", 86 ),
            new Tuple<string, int>( "god-is-love", 87 ),
            new Tuple<string, int>( "great-god-attend-while-zion-sings", 88 ),
            new Tuple<string, int>( "the-lord-is-my-light", 89 ),
            new Tuple<string, int>( "from-all-that-dwell-below-the-skies", 90 ),
            new Tuple<string, int>( "father-thy-children-to-thee-now-raise", 91 ),
            new Tuple<string, int>( "for-the-beauty-of-the-earth", 92 ),
            new Tuple<string, int>( "prayer-of-thanksgiving", 93 ),
            new Tuple<string, int>( "come-ye-thankful-people", 94 ),
            new Tuple<string, int>( "now-thank-we-all-our-god", 95 ),
            new Tuple<string, int>( "dearest-children-god-is-near-you", 96 ),
            new Tuple<string, int>( "lead-kindly-light", 97 ),
            new Tuple<string, int>( "i-need-thee-every-hour", 98 ),
            new Tuple<string, int>( "nearer-dear-savior-to-thee", 99 ),
            new Tuple<string, int>( "nearer-my-god-to-thee", 100 ),
            new Tuple<string, int>( "guide-me-to-thee", 101 ),
            new Tuple<string, int>( "jesus-lover-of-my-soul", 102 ),
            new Tuple<string, int>( "precious-savior-dear-redeemer", 103 ),
            new Tuple<string, int>( "jesus-savior-pilot-me", 104 ),
            new Tuple<string, int>( "master-the-tempest-is-raging", 105 ),
            new Tuple<string, int>( "god-speed-the-right", 106 ),
            new Tuple<string, int>( "lord-accept-our-true-devotion", 107 ),
            new Tuple<string, int>( "the-lord-is-my-shepherd", 108 ),
            new Tuple<string, int>( "the-lord-my-pasture-will-prepare", 109 ),
            new Tuple<string, int>( "cast-thy-burden-upon-the-lord", 110 ),
            new Tuple<string, int>( "rock-of-ages", 111 ),
            new Tuple<string, int>( "savior-redeemer-of-my-soul", 112 ),
            new Tuple<string, int>( "our-saviors-love", 113 ),
            new Tuple<string, int>( "come-unto-him", 114 ),
            new Tuple<string, int>( "come-ye-disconsolate", 115 ),
            new Tuple<string, int>( "come-follow-me", 116 ),
            new Tuple<string, int>( "come-unto-jesus", 117 ),
            new Tuple<string, int>( "ye-simple-souls-who-stray", 118 ),
            new Tuple<string, int>( "come-we-that-love-the-lord", 119 ),
            new Tuple<string, int>( "lean-on-my-ample-arm", 120 ),
            new Tuple<string, int>( "im-a-pilgrim-im-a-stranger", 121 ),
            new Tuple<string, int>( "though-deepening-trials", 122 ),
            new Tuple<string, int>( "oh-may-my-soul-commune-with-thee", 123 ),
            new Tuple<string, int>( "be-still-my-soul", 124 ),
            new Tuple<string, int>( "how-gentle-gods-commands", 125 ),
            new Tuple<string, int>( "how-long-o-lord-most-holy-and-true", 126 ),
            new Tuple<string, int>( "does-the-journey-seem-long", 127 ),
            new Tuple<string, int>( "when-faith-endures", 128 ),
            new Tuple<string, int>( "where-can-i-turn-for-peace", 129 ),
            new Tuple<string, int>( "be-thou-humble", 130 ),
            new Tuple<string, int>( "more-holiness-give-me", 131 ),
            new Tuple<string, int>( "god-is-in-his-holy-temple", 132 ),
            new Tuple<string, int>( "father-in-heaven", 133 ),
            new Tuple<string, int>( "i-believe-in-christ", 134 ),
            new Tuple<string, int>( "my-redeemer-lives", 135 ),
            new Tuple<string, int>( "i-know-that-my-redeemer-lives", 136 ),
            new Tuple<string, int>( "testimony", 137 ),
            new Tuple<string, int>( "bless-our-fast-we-pray", 138 ),
            new Tuple<string, int>( "in-fasting-we-approach-thee", 139 ),
            new Tuple<string, int>( "did-you-think-to-pray", 140 ),
            new Tuple<string, int>( "jesus-the-very-thought-of-thee", 141 ),
            new Tuple<string, int>( "sweet-hour-of-prayer", 142 ),
            new Tuple<string, int>( "let-the-holy-spirit-guide", 143 ),
            new Tuple<string, int>( "secret-prayer", 144 ),
            new Tuple<string, int>( "prayer-is-the-souls-sincere-desire", 145 ),
            new Tuple<string, int>( "gently-raise-the-sacred-strain", 146 ),
            new Tuple<string, int>( "sweet-is-the-work", 147 ),
            new Tuple<string, int>( "sabbath-day", 148 ),
            new Tuple<string, int>( "as-the-dew-from-heaven-distilling", 149 ),
            new Tuple<string, int>( "o-thou-kind-and-gracious-father", 150 ),
            new Tuple<string, int>( "we-meet-dear-lord", 151 ),
            new Tuple<string, int>( "god-be-with-you-till-we-meet-again", 152 ),
            new Tuple<string, int>( "lord-we-ask-thee-ere-we-part", 153 ),
            new Tuple<string, int>( "father-this-hour-has-been-one-of-joy", 154 ),
            new Tuple<string, int>( "we-have-partaken-of-thy-love", 155 ),
            new Tuple<string, int>( "sing-we-now-at-parting", 156 ),
            new Tuple<string, int>( "thy-spirit-lord-has-stirred-our-souls", 157 ),
            new Tuple<string, int>( "before-thee-lord-i-bow-my-head", 158 ),
            new Tuple<string, int>( "now-the-day-is-over", 159 ),
            new Tuple<string, int>( "softly-now-the-light-of-day", 160 ),
            new Tuple<string, int>( "the-lord-be-with-us", 161 ),
            new Tuple<string, int>( "lord-we-come-before-thee-now", 162 ),
            new Tuple<string, int>( "lord-dismiss-us-with-thy-blessing", 163 ),
            new Tuple<string, int>( "great-god-to-thee-my-evening-song", 164 ),
            new Tuple<string, int>( "abide-with-me-tis-eventide", 165 ),
            new Tuple<string, int>( "abide-with-me", 166 ),
            new Tuple<string, int>( "come-let-us-sing-an-evening-hymn", 167 ),
            new Tuple<string, int>( "as-the-shadows-fall", 168 ),
            new Tuple<string, int>( "as-now-we-take-the-sacrament", 169 ),
            new Tuple<string, int>( "god-our-father-hear-us-pray", 170 ),
            new Tuple<string, int>( "with-humble-heart", 171 ),
            new Tuple<string, int>( "in-humility-our-savior", 172 ),
            new Tuple<string, int>( "while-of-these-emblems-we-partake-saul", 173 ),
            new Tuple<string, int>( "while-of-these-emblems-we-partake-aeolian", 174 ),
            new Tuple<string, int>( "o-god-the-eternal-father", 175 ),
            new Tuple<string, int>( "tis-sweet-to-sing-the-matchless-love-meredith", 176 ),
            new Tuple<string, int>( "tis-sweet-to-sing-the-matchless-love-hancock", 177 ),
            new Tuple<string, int>( "o-lord-of-hosts", 178 ),
            new Tuple<string, int>( "again-our-dear-redeeming-lord", 179 ),
            new Tuple<string, int>( "father-in-heaven-we-do-believe", 180 ),
            new Tuple<string, int>( "jesus-of-nazareth-savior-and-king", 181 ),
            new Tuple<string, int>( "well-sing-all-hail-to-jesus-name", 182 ),
            new Tuple<string, int>( "in-remembrance-of-thy-suffering", 183 ),
            new Tuple<string, int>( "upon-the-cross-of-calvary", 184 ),
            new Tuple<string, int>( "reverently-and-meekly-now", 185 ),
            new Tuple<string, int>( "again-we-meet-around-the-board", 186 ),
            new Tuple<string, int>( "god-loved-us-so-he-sent-his-son", 187 ),
            new Tuple<string, int>( "thy-will-o-lord-be-done", 188 ),
            new Tuple<string, int>( "o-thou-before-the-world-began", 189 ),
            new Tuple<string, int>( "in-memory-of-the-crucified", 190 ),
            new Tuple<string, int>( "behold-the-great-redeemer-die", 191 ),
            new Tuple<string, int>( "he-died-the-great-redeemer-died", 192 ),
            new Tuple<string, int>( "i-stand-all-amazed", 193 ),
            new Tuple<string, int>( "there-is-a-green-hill-far-away", 194 ),
            new Tuple<string, int>( "how-great-the-wisdom-and-the-love", 195 ),
            new Tuple<string, int>( "jesus-once-of-humble-birth", 196 ),
            new Tuple<string, int>( "o-savior-thou-who-wearest-a-crown", 197 ),
            new Tuple<string, int>( "that-easter-morn", 198 ),
            new Tuple<string, int>( "he-is-risen", 199 ),
            new Tuple<string, int>( "christ-the-lord-is-risen-today", 200 ),
            new Tuple<string, int>( "joy-to-the-world", 201 ),
            new Tuple<string, int>( "oh-come-all-ye-faithful", 202 ),
            new Tuple<string, int>( "angels-we-have-heard-on-high", 203 ),
            new Tuple<string, int>( "silent-night", 204 ),
            new Tuple<string, int>( "once-in-royal-davids-city", 205 ),
            new Tuple<string, int>( "away-in-a-manger", 206 ),
            new Tuple<string, int>( "it-came-upon-the-midnight-clear", 207 ),
            new Tuple<string, int>( "o-little-town-of-bethlehem", 208 ),
            new Tuple<string, int>( "hark-the-herald-angels-sing", 209 ),
            new Tuple<string, int>( "with-wondering-awe", 210 ),
            new Tuple<string, int>( "while-shepherds-watched-their-flocks", 211 ),
            new Tuple<string, int>( "far-far-away-on-judeas-plains", 212 ),
            new Tuple<string, int>( "the-first-noel", 213 ),
            new Tuple<string, int>( "i-heard-the-bells-on-christmas-day", 214 ),
            new Tuple<string, int>( "ring-out-wild-bells", 215 ),
            new Tuple<string, int>( "we-are-sowing", 216 ),
            new Tuple<string, int>( "come-let-us-anew", 217 ),
            new Tuple<string, int>( "we-give-thee-but-thine-own", 218 ),
            new Tuple<string, int>( "because-i-have-been-given-much", 219 ),
            new Tuple<string, int>( "lord-i-would-follow-thee", 220 ),
            new Tuple<string, int>( "dear-to-the-heart-of-the-shepherd", 221 ),
            new Tuple<string, int>( "hear-thou-our-hymn-o-lord", 222 ),
            new Tuple<string, int>( "have-i-done-any-good", 223 ),
            new Tuple<string, int>( "i-have-work-enough-to-do", 224 ),
            new Tuple<string, int>( "we-are-marching-on-to-glory", 225 ),
            new Tuple<string, int>( "improve-the-shining-moments", 226 ),
            new Tuple<string, int>( "there-is-sunshine-in-my-soul-today", 227 ),
            new Tuple<string, int>( "you-can-make-the-pathway-bright", 228 ),
            new Tuple<string, int>( "today-while-the-sun-shines", 229 ),
            new Tuple<string, int>( "scatter-sunshine", 230 ),
            new Tuple<string, int>( "father-cheer-our-souls-tonight", 231 ),
            new Tuple<string, int>( "let-us-oft-speak-kind-words", 232 ),
            new Tuple<string, int>( "nay-speak-no-ill", 233 ),
            new Tuple<string, int>( "jesus-mighty-king-in-zion", 234 ),
            new Tuple<string, int>( "should-you-feel-inclined-to-censure", 235 ),
            new Tuple<string, int>( "lord-accept-into-thy-kingdom", 236 ),
            new Tuple<string, int>( "do-what-is-right", 237 ),
            new Tuple<string, int>( "behold-thy-sons-and-daughters-lord", 238 ),
            new Tuple<string, int>( "choose-the-right", 239 ),
            new Tuple<string, int>( "know-this-that-every-soul-is-free", 240 ),
            new Tuple<string, int>( "count-your-blessings", 241 ),
            new Tuple<string, int>( "praise-god-from-whom-all-blessings-flow", 242 ),
            new Tuple<string, int>( "let-us-all-press-on", 243 ),
            new Tuple<string, int>( "come-along-come-along", 244 ),
            new Tuple<string, int>( "this-house-we-dedicate-to-thee", 245 ),
            new Tuple<string, int>( "onward-christian-soldiers", 246 ),
            new Tuple<string, int>( "we-love-thy-house-o-god", 247 ),
            new Tuple<string, int>( "up-awake-ye-defenders-of-zion", 248 ),
            new Tuple<string, int>( "called-to-serve", 249 ),
            new Tuple<string, int>( "we-are-all-enlisted", 250 ),
            new Tuple<string, int>( "behold-a-royal-army", 251 ),
            new Tuple<string, int>( "put-your-shoulder-to-the-wheel", 252 ),
            new Tuple<string, int>( "like-ten-thousand-legions-marching", 253 ),
            new Tuple<string, int>( "true-to-the-faith", 254 ),
            new Tuple<string, int>( "carry-on", 255 ),
            new Tuple<string, int>( "as-zions-youth-in-latter-days", 256 ),
            new Tuple<string, int>( "rejoice-a-glorious-sound-is-heard", 257 ),
            new Tuple<string, int>( "o-thou-rock-of-our-salvation", 258 ),
            new Tuple<string, int>( "hope-of-israel", 259 ),
            new Tuple<string, int>( "whos-on-the-lords-side", 260 ),
            new Tuple<string, int>( "thy-servants-are-prepared", 261 ),
            new Tuple<string, int>( "go-ye-messengers-of-glory", 262 ),
            new Tuple<string, int>( "go-forth-with-faith", 263 ),
            new Tuple<string, int>( "hark-all-ye-nations", 264 ),
            new Tuple<string, int>( "arise-o-god-and-shine", 265 ),
            new Tuple<string, int>( "the-time-is-far-spent", 266 ),
            new Tuple<string, int>( "how-wondrous-and-great", 267 ),
            new Tuple<string, int>( "come-all-whose-souls-are-lighted", 268 ),
            new Tuple<string, int>( "jehovah-lord-of-heaven-and-earth", 269 ),
            new Tuple<string, int>( "ill-go-where-you-want-me-to-go", 270 ),
            new Tuple<string, int>( "oh-holy-words-of-truth-and-love", 271 ),
            new Tuple<string, int>( "oh-say-what-is-truth", 272 ),
            new Tuple<string, int>( "truth-reflects-upon-our-senses", 273 ),
            new Tuple<string, int>( "the-iron-rod", 274 ),
            new Tuple<string, int>( "men-are-that-they-might-have-joy", 275 ),
            new Tuple<string, int>( "come-away-to-the-sunday-school", 276 ),
            new Tuple<string, int>( "as-i-search-the-holy-scriptures", 277 ),
            new Tuple<string, int>( "thanks-for-the-sabbath-school", 278 ),
            new Tuple<string, int>( "thy-holy-word", 279 ),
            new Tuple<string, int>( "welcome-welcome-sabbath-morning", 280 ),
            new Tuple<string, int>( "help-me-teach-with-inspiration", 281 ),
            new Tuple<string, int>( "we-meet-again-in-sabbath-school", 282 ),
            new Tuple<string, int>( "the-glorious-gospel-light-has-shone", 283 ),
            new Tuple<string, int>( "if-you-could-hie-to-kolob", 284 ),
            new Tuple<string, int>( "god-moves-in-a-mysterious-way", 285 ),
            new Tuple<string, int>( "oh-what-songs-of-the-heart", 286 ),
            new Tuple<string, int>( "rise-ye-saints-and-temples-enter", 287 ),
            new Tuple<string, int>( "how-beautiful-thy-temples-lord", 288 ),
            new Tuple<string, int>( "holy-temples-on-mount-zion", 289 ),
            new Tuple<string, int>( "rejoice-ye-saints-of-latter-days", 290 ),
            new Tuple<string, int>( "turn-your-hearts", 291 ),
            new Tuple<string, int>( "o-my-father", 292 ),
            new Tuple<string, int>( "each-life-that-touches-ours-for-good", 293 ),
            new Tuple<string, int>( "love-at-home", 294 ),
            new Tuple<string, int>( "o-love-that-glorifies-the-son", 295 ),
            new Tuple<string, int>( "our-father-by-whose-name", 296 ),
            new Tuple<string, int>( "from-homes-of-saints-glad-songs-arise", 297 ),
            new Tuple<string, int>( "home-can-be-a-heaven-on-earth", 298 ),
            new Tuple<string, int>( "children-of-our-heavenly-father", 299 ),
            new Tuple<string, int>( "families-can-be-together-forever", 300 ),
            new Tuple<string, int>( "i-am-a-child-of-god", 301 ),
            new Tuple<string, int>( "i-know-my-father-lives", 302 ),
            new Tuple<string, int>( "keep-the-commandments", 303 ),
            new Tuple<string, int>( "teach-me-to-walk-in-the-light", 304 ),
            new Tuple<string, int>( "the-light-divine", 305 ),
            new Tuple<string, int>( "gods-daily-care", 306 ),
            new Tuple<string, int>( "in-our-lovely-deseret", 307 ),
            new Tuple<string, int>( "love-one-another", 308 ),
            new Tuple<string, int>( "as-sisters-in-zion", 309 ),
            new Tuple<string, int>( "a-key-was-turned-in-latter-days", 310 ),
            new Tuple<string, int>( "we-meet-again-as-sisters", 311 ),
            new Tuple<string, int>( "we-ever-pray-for-thee-women", 312 ),
            new Tuple<string, int>( "god-is-love-women", 313 ),
            new Tuple<string, int>( "how-gentle-gods-commands-women", 314 ),
            new Tuple<string, int>( "jesus-the-very-thought-of-thee-women", 315 ),
            new Tuple<string, int>( "the-lord-is-my-shepherd-women", 316 ),
            new Tuple<string, int>( "sweet-is-the-work-women", 317 ),
            new Tuple<string, int>( "love-at-home-women", 318 ),
            new Tuple<string, int>( "ye-elders-of-israel", 319 ),
            new Tuple<string, int>( "the-priesthood-of-our-lord", 320 ),
            new Tuple<string, int>( "ye-who-are-called-to-labor", 321 ),
            new Tuple<string, int>( "come-all-ye-sons-of-god", 322 ),
            new Tuple<string, int>( "rise-up-o-men-of-god-mens-choir", 323 ),
            new Tuple<string, int>( "rise-up-o-men-of-god", 324 ),
            new Tuple<string, int>( "see-the-mighty-priesthood-gathered", 325 ),
            new Tuple<string, int>( "come-come-ye-saints-mens-choir", 326 ),
            new Tuple<string, int>( "go-ye-messengers-of-heaven-mens-choir", 327 ),
            new Tuple<string, int>( "an-angel-from-on-high-mens-choir", 328 ),
            new Tuple<string, int>( "thy-servants-are-prepared-men", 329 ),
            new Tuple<string, int>( "see-the-mighty-angel-flying-mens-choir", 330 ),
            new Tuple<string, int>( "oh-say-what-is-truth-mens-choir", 331 ),
            new Tuple<string, int>( "come-o-thou-king-of-kings-mens-choir", 332 ),
            new Tuple<string, int>( "high-on-the-mountain-top-mens-choir", 333 ),
            new Tuple<string, int>( "i-need-thee-every-hour-mens-choir", 334 ),
            new Tuple<string, int>( "brightly-beams-our-fathers-mercy-mens-choir", 335 ),
            new Tuple<string, int>( "school-thy-feelings", 336 ),
            new Tuple<string, int>( "o-home-beloved", 337 ),
            new Tuple<string, int>( "america-the-beautiful", 338 ),
            new Tuple<string, int>( "my-country-tis-of-thee", 339 ),
            new Tuple<string, int>( "the-star-spangled-banner", 340 ),
            new Tuple<string, int>( "god-save-the-king", 341 ),
            new Tuple<string, int>( "come-thou-fount-of-every-blessing", 1001 ),
            new Tuple<string, int>( "when-the-savior-comes-again", 1002 ),
            new Tuple<string, int>( "it-is-well-with-my-soul", 1003 ),
            new Tuple<string, int>( "i-will-walk-with-jesus", 1004 ),
            new Tuple<string, int>( "his-eye-is-on-the-sparrow", 1005 ),
            new Tuple<string, int>( "think-a-sacred-song", 1006 ),
            new Tuple<string, int>( "as-bread-is-broken", 1007 ),
            new Tuple<string, int>( "bread-of-life-living-water", 1008 ),
            new Tuple<string, int>( "gethsemane", 1009 ),
            new Tuple<string, int>( "amazing-grace", 1010 ),
            new Tuple<string, int>( "holding-hands-around-the-world", 1011 ),
            new Tuple<string, int>( "anytime-anywhere", 1012 ),
            new Tuple<string, int>( "gods-gracious-love", 1013 ),
            new Tuple<string, int>( "my-shepherd-will-supply-my-need", 1014 ),
            new Tuple<string, int>( "oh-the-deep-deep-love-of-jesus", 1015 ),
            new Tuple<string, int>( "behold-the-wounds-in-jesus-hands", 1016 ),
            new Tuple<string, int>( "this-is-the-christ", 1017 ),
            new Tuple<string, int>( "come-lord-jesus", 1018 ),
            new Tuple<string, int>( "to-love-like-thee-release-3", 1019 ),
            new Tuple<string, int>( "softly-and-tenderly-jesus-is-calling-release-3", 1020 ),
            new Tuple<string, int>( "i-know-that-my-savior-loves-me-release-3", 1021 ),
            new Tuple<string, int>( "faith-in-every-footstep-release-3", 1022 ),
            new Tuple<string, int>( "standing-on-the-promises-release-3", 1023 ),
            new Tuple<string, int>( "i-have-faith-in-the-lord-jesus-christ-release-3", 1024 ),
            new Tuple<string, int>( "take-my-heart-and-let-it-be-consecrated-release-3", 1025 ),
            new Tuple<string, int>( "holy-places-release-3", 1026 ),
            new Tuple<string, int>( "welcome-home-release-3", 1027 ),
            new Tuple<string, int>( "this-little-light-of-mine-release-3", 1028 ),
            new Tuple<string, int>( "i-cant-count-them-all-release-3", 1029 ),
            new Tuple<string, int>( "close-as-a-quiet-prayer-release-3", 1030 ),
            new Tuple<string, int>( "come-hear-the-word-the-lord-has-spoken-release-3", 1031 ),
            new Tuple<string, int>( "look-unto-christ", 1032 ),
            new Tuple<string, int>( "oh-how-great-is-our-joy", 1033 ),
            new Tuple<string, int>( "im-a-pioneer-too", 1034 ),
            new Tuple<string, int>( "as-i-keep-the-sabbath-day", 1035 ),
            new Tuple<string, int>( "read-the-book-of-mormon-and-pray", 1036 ),
            new Tuple<string, int>( "im-gonna-live-so-god-can-use-me", 1037 ),
            new Tuple<string, int>( "the-lords-my-shepherd", 1038 ),
            new Tuple<string, int>( "because", 1039 ),
            new Tuple<string, int>( "his-voice-as-the-sound", 1040 ),
            new Tuple<string, int>( "o-lord-who-gave-thy-life-for-me", 1041 ),
            new Tuple<string, int>( "thou-gracious-god-whose-mercy-lends", 1042 ),
            new Tuple<string, int>( "help-us-remember", 1043 ),
            new Tuple<string, int>( "how-did-the-savior-minister", 1044 ),
            new Tuple<string, int>( "jesus-is-the-way", 1045 ),
            new Tuple<string, int>( "can-you-count-the-stars-in-heaven", 1046 ),
            new Tuple<string, int>( "he-cares-for-me", 1047 ),
            new Tuple<string, int>( "our-prayer-to-thee", 1048 ),
            new Tuple<string, int>( "joseph-prayed-in-faith", 1049 ),
            new Tuple<string, int>( "stand-by-me", 1050 ),
            new Tuple<string, int>( "this-day-is-a-good-day-lord", 1051 ),
            new Tuple<string, int>( "hail-the-day-that-sees-him-rise", 1201 ),
            new Tuple<string, int>( "he-is-born-the-divine-christ-child", 1202 ),
            new Tuple<string, int>( "what-child-is-this", 1203 ),
            new Tuple<string, int>( "star-bright", 1204 ),
            new Tuple<string, int>( "let-easter-anthems-ring-release-3", 1205 ),
            new Tuple<string, int>( "were-you-there-release-3", 1206 ),
            new Tuple<string, int>( "still-still-still", 1207 ),
            new Tuple<string, int>( "go-tell-it-on-the-mountain", 1208 ),
            new Tuple<string, int>( "little-baby-in-a-manger", 1209 )
        };

        private static readonly IReadOnlyDictionary<string, int> HYMN_ID_TO_NUMBER;
        private static readonly IReadOnlyDictionary<int, string> HYMN_NUMBER_TO_ID;

        static HymnMetadataEnglish()
        {
            Dictionary<string, int> idToNumber = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
            Dictionary<int, string> numberToId = new Dictionary<int, string>();

            foreach (var hymn in ENGLISH_HYMNAL)
            {
                idToNumber[hymn.Item1] = hymn.Item2;
                numberToId[hymn.Item2] = hymn.Item1;
            }

            HYMN_ID_TO_NUMBER = idToNumber;
            HYMN_NUMBER_TO_ID = numberToId;
        }

        public static string GetHymnId(int hymnNumber)
        {
            return HYMN_NUMBER_TO_ID[hymnNumber];
        }

        public static bool TryGetHymnId(int hymnNumber, [NotNullWhen(true)] out string? hymnId)
        {
            return HYMN_NUMBER_TO_ID.TryGetValue(hymnNumber, out hymnId);
        }

        public static int GetHymnNumber(string hymnId)
        {
            return HYMN_ID_TO_NUMBER[hymnId];
        }

        public static bool TryGetHymnNumber(string hymnId, out int hymnNumber)
        {
            return HYMN_ID_TO_NUMBER.TryGetValue(hymnId, out hymnNumber);
        }

        public static IEnumerable<string> GetAllHymnIds()
        {
            return HYMN_ID_TO_NUMBER.Keys;
        }
    }
}
